name: EasyWax
version: 1.0.0
main: me.miicro.easywax.EasyWax
description: Allows waxing signs without honeycomb
author: miicro
api-version: "1.21.11"
commands:
  waxit:
    description: Waxes the sign that the player punches. Punching any other block cancels the command
    usage: /waxit